[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bp_text"
dynamic = ["version"]
description = "Python algorithmic text generation tools."
authors = [
    { name = "Ruben Philipp", email = "me@rubenphilipp.com" }
]
license = "GPL-3.0-or-later"
readme = "readme.md"
requires-python = ">=3.8"
dependencies = [
    # "requests>=2.26.0",
    "numpy>=1.21.0",
    "lingua-language-detector>=2.1.0",
    # "flair>=0.15.0",
    "spacy>=3.8.2",
    "pdf2image>=1.17.0",
    "pytesseract>=0.3.13",
    # "PyPDF2>=3.0.1",
    "pypdf>=3.9.1",
    "bibtexparser>=2.0.0b8",
    "roman>=5.0",
    "langcodes>=3.5.0"
]

[tool.setuptools.dynamic]
version = { attr = "bp_text.__version__" }

[project.optional-dependencies]
dev = ["pytest", "black", "flake8"]
docs = ["sphinx", "sphinx-rtd-theme"]

[tool.setuptools]
packages = ["bp_text"]

[tool.black]
line-length = 88

# [tool.pytest.ini_options]
# testpaths = ["tests"]

