name: Deploy Python Sphinx Docs

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkoud the repository
        uses: actions/checkout@v3
        
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'

      # - name: Install dependencies
      #   run: |
      #     pip install 'python/'
      #     pip install 'python/[docs]'

      # - name: Build the documentation
      #   run: |
      #     cd python/docs
      #     make clean && make html

      - name: Copy additional docs from main/docs
        run: |
          mkdir -p temp/docs
          cp -r docs/* temp/docs/

      - name: Prepare deployment directory
        run: |
          mkdir -p final-deploy/docs/python
          cp -r temp/docs final-deploy/
          cp -r python/docs/build/html/* final-deploy/docs/python/
          touch final-deploy/docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: final-deploy/docs
          target-folder: docs
          clean: false
